### ISSUE TITLE
Convert ng2 app to use CLI and ng2 rc1

### ISSUE THREAD

**Issue by splintercode** [vintage-software/vstack-demo#9]
We will want to migrate the demo app to use the Angular 2 CLI instead of our custom gulp tasks.

https://cli.angular.io/

**Comment by steve-haar** [comment]
Started working on this.

**Comment by splintercode** [comment]
Awesome, You can look at this repo for CLI examples if you want. 
https://github.com/splintercode/focus

I also have a private repo that has the vstack graph integrated into the CLI project.

**Comment by steve-haar** [comment]
Finished, but node server is not working now since it's not part of the cli.
